---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 2919976297-jHcSyNqcw2Thajo3R3N87sNsbLLpPQjKLkAjAaM
:access_token_secret: WbeZJDqNwZ2QGMIHodXP3cqOLoaj5s5HanXD1iIwSPA4U
